### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Controlzubi** [LoseBypass/issues#29]
Game is Crashing randomly with this Error Code: "Exception ticking world"

**Comment by wallhacks0** [comment]
Hi, this is a very common error code and hard for us to say what it is. It would help if you attach logs and explain what was happening before you crashed.

**Comment by Controlzubi** [comment]
Thats the Crash Report

Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at rip.breeze.client.eh.a(njBBIB2Q8r5xL9xFV84aWw==:17423)
	at adm.setBlockState$a$CInject0(SourceFile:29)
	at adm.a(SourceFile:289)
	at apj.b(SourceFile:70)
	at aeb.a(SourceFile:317)
	at aeb.a(SourceFile:333)
	at aeb.a(SourceFile:92)
	at aeb.a(SourceFile:49)
	at ady.a(SourceFile:388)
	at aoa.a(SourceFile:473)
	at ld.a(SourceFile:174)
	at amy.a(SourceFile:866)
	at ld.c(SourceFile:104)
	at ld.d(SourceFile:116)
	at adm.a(SourceFile:277)
	at le.h(SourceFile:327)
	at le.c(SourceFile:202)
	at net.minecraft.server.MinecraftServer.B(SourceFile:599)
	at net.minecraft.server.MinecraftServer.A(SourceFile:535)
	at bpo.A(IntegratedServer.java:281)
	at net.minecraft.server.MinecraftServer.run(SourceFile:451)
	at java.lang.Thread.run(Thread.java:750)

**Comment by wallhacks0** [comment]
thanks!

**Comment by Controlzubi** [comment]
Just realised that my game most of the time crashes if i use killaura

**Comment by NotBoru** [comment]
> Just realised that my game most of the time crashes if i use killaura

same
