### ISSUE TITLE
[BUG] Game Freezes Mid PVP for a very long time

### ISSUE THREAD

**Issue by ghost** [LoseBypass/issues#30]
**Describe the bug**
A clear and concise description of what the bug is, and where you want it to be added (client, website etc).

sometimes in the prod release, your game will freeze mid pvp

**To Reproduce**

1. log on hypixel
2. get on bedwars
3. keep fighting people
4. you will soon get the issue

**Expected behavior**

i continue to play the game

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 11] (please include version)

**Additional context**

desktop
windows 10

log after forcefully stopping the game when it freezes

java.lang.NullPointerException
	at rip.breeze.client.hd.a(y7o5btV065MVRH1DoqImUA==:18716)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at rip.breeze.client.eh.a(VuB3GK4hwVgYuSrOibK/Cg==:50823)
	at bfk.renderWorld$b$CInject0(EntityRenderer.java:227)
	at bfk.b(EntityRenderer.java:1591)
	at bfk.a(EntityRenderer.java:1377)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at rip.breeze.loader.Main.main(Native Method)
java.lang.NullPointerException
	at rip.breeze.client.hd.a(y7o5btV065MVRH1DoqImUA==:18716)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at rip.breeze.client.eh.a(VuB3GK4hwVgYuSrOibK/Cg==:50823)
	at bfk.renderWorld$b$CInject0(EntityRenderer.java:227)
	at bfk.b(EntityRenderer.java:1591)
	at bfk.a(EntityRenderer.java:1377)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at rip.breeze.loader.Main.main(Native Method)
java.lang.NullPointerException
	at rip.breeze.client.hd.a(y7o5btV065MVRH1DoqImUA==:18716)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at rip.breeze.client.eh.a(VuB3GK4hwVgYuSrOibK/Cg==:50823)
	at bfk.renderWorld$b$CInject0(EntityRenderer.java:227)
	at bfk.b(EntityRenderer.java:1591)
	at bfk.a(EntityRenderer.java:1377)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at rip.breeze.loader.Main.main(Native Method)
java.lang.NullPointerException
	at rip.breeze.client.hd.a(y7o5btV065MVRH1DoqImUA==:18716)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)

**Comment by ghost** [comment]
no clue why i keep getting a null pointer exception, this time though i got a java.util.concurrentmodificationexception, my friend isn't having the same issue, its NOT my internet, ive tried removing the rip.breeze folder from localappdata

**Comment by ghost** [comment]
If you use forge breeze the issue is fixed

**Comment by qhonk** [comment]
It the antibot feature idk why but it the problem
